### ISSUE TITLE
undefined method `sec`

### ISSUE THREAD

**Issue by negativeOne1** [scalyr/scalyr-fluentd#8]
Hi,

I have the scalyr-fluentd 0.8.1 plugin installed in a fluentd-0.14.25 container, unfortunately I'm running into issues when I try to send some logs using python and fluent-logger 0.6.2.

```
~ ❯❯❯ kubectl logs -f fluentd-z7zhq                                       
2017-12-04 16:21:29 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2017-12-04 16:21:29 +0000 [warn]: Pre 0.14.0 configuration file detected.  Please consider updating your configuration file
2017-12-04 16:21:29 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    port 24224
  </source>
  <match **>
    @type scalyr
    api_write_token "<REMOVED_TOKEN>"
    ssl_ca_bundle_path "/etc/ssl/certs/ca-certificates.crt"
  </match>
</ROOT>
2017-12-04 16:21:29 +0000 [info]: starting fluentd-0.14.25 pid=5 ruby="2.3.5"
2017-12-04 16:21:29 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2017-12-04 16:21:30 +0000 [info]: gem 'fluent-plugin-scalyr' version '0.8.1'
2017-12-04 16:21:30 +0000 [info]: gem 'fluentd' version '0.14.25'
2017-12-04 16:21:30 +0000 [info]: adding match pattern="**" type="scalyr"
2017-12-04 16:21:30 +0000 [warn]: #0 Pre 0.14.0 configuration file detected.  Please consider updating your configuration file
2017-12-04 16:21:30 +0000 [info]: adding source type="forward"
2017-12-04 16:21:30 +0000 [info]: #0 starting fluentd worker pid=15 ppid=5 worker=0
2017-12-04 16:21:30 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
2017-12-04 16:21:30 +0000 [info]: #0 fluentd worker is now running worker=0
```

```python
from fluent import sender

logger = sender.FluentSender('test_app')

logger.emit('test_trace',
            {'from': 'A',
             'to': 'B'})
```

```
2017-12-04 16:16:58 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `sec' for 1512404218:Fixnum\nDid you mean?  send" location="/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-scalyr-0.8.1/lib/fluent/plugin/out_scalyr.rb:131:in `format'" tag="test_app.test_trace"
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-scalyr-0.8.1/lib/fluent/plugin/out_scalyr.rb:131:in `format'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:956:in `block in handle_stream_simple'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/event.rb:107:in `each'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:955:in `handle_stream_simple'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:841:in `execute_chunking'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:771:in `emit_buffered'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/event_router.rb:96:in `emit_stream'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/event_router.rb:87:in `emit'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:337:in `on_message'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:211:in `block in handle_connection'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:248:in `block (3 levels) in read_messages'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:247:in `feed_each'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:247:in `block (2 levels) in read_messages'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/in_forward.rb:256:in `block in read_messages'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin_helper/server.rb:588:in `on_read_without_connection'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:123:in `on_readable'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:186:in `on_readable'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
  2017-12-04 16:16:58 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-12-04 16:16:58 +0000 [error]: #0 unexpected error on reading data host="127.0.0.1" port=48046 error_class=NoMethodError error="undefined method `sec' for 1512404218:Fixnum\nDid you mean?  send"
  2017-12-04 16:16:58 +0000 [error]: #0 suppressed same stacktrace
```

**Comment by imron** [comment]
Fluentd passes in a timestamp variable to the scalyr-fluentd plugin, and the plugin expects the timestamp to be non nil.  


It would appear that the logger.emit() function of the python fluent-logger tool does not include a timestamp unless you call:

logger.emit_with_time(...)

The fluent-0.14 branch also expects these timestamps to be in the newer 0.14 nanosecond compatible format, so you'll need to make sure you enable that also in the FluentSender object in python.

There's an example of how to do this on the [Fluent Logger](https://pypi.python.org/pypi/fluent-logger/) page on pypi.  Clicking that link and searching for 'nanosecond' should get you the relevant example.

Let me know if that works.

**Comment by negativeOne1** [comment]
``` 
import time                                                                         
from fluent import asyncsender as sender                                            
                                                                                    
logger = sender.FluentSender('app', nanosecond_precision=True)                      
logger.emit_with_time('follow', time.time(), {'from': 'userA', 'to': 'userB'})   
                                                                                    
logger.close()   
```

doesn't work ether.  Nothing in the logs, nothing on scalyr.

**Comment by negativeOne1** [comment]
OK, now it seams to work. I forgot that I used the `asyncsender` and that doesn't seam to work.

**Comment by imron** [comment]
Ok, glad to hear it's working.  I'll close the issue.

I see as well from your output that you're using Kubernetes.  We plan to have built-in support for Kubernetes in an upcoming release of the Scalyr Agent, which will run as a Daemonset on all nodes in your cluster, so that might be able to help reduce the moving parts and dependencies and the need to run fluentd.
